# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-13 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potlakosubject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='citizenship',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], max_length=2, null=True, verbose_name=' citizen of Botswana?'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='legally_married',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], max_length=2, null=True, verbose_name='legally married to a Botswana Citizen?'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='literacy',
            field=models.CharField(blank=True, choices=[('literate', 'literate'), ('illiterate', 'illiterate')], max_length=10, null=True, verbose_name='is the participant literate or illiterate?'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='marriage_certificate',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], max_length=2, null=True, verbose_name='has the participant produced marriage certificate as proof ?'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='minor',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], max_length=2, null=True, verbose_name='If minor, is there a guardian available?'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=4, verbose_name='Gender '),
        ),
    ]
