# Generated by Django 3.1.4 on 2021-02-01 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('potlakosubject', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommunityEngagementQuestionnare',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='SubjectConsent',
        ),
    ]
