# Generated by Django 3.1.4 on 2021-01-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potlakosubject', '0002_auto_20210113_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='citizenship',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], max_length=5, null=True, verbose_name='Citizen of Botswana?'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10, verbose_name='Gender '),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='legally_married',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], max_length=5, null=True, verbose_name='Legally married to a Botswana Citizen?'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='literacy',
            field=models.CharField(blank=True, choices=[('literate', 'literate'), ('illiterate', 'illiterate')], max_length=20, null=True, verbose_name='Is the participant literate or illiterate?'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='marriage_certificate',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], max_length=5, null=True, verbose_name='Has the participant produced marriage certificate as proof?'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='minor',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], max_length=5, null=True, verbose_name='If minor, is there a guardian available?'),
        ),
    ]
