# Generated by Django 3.1.4 on 2021-01-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potlakosubject', '0003_auto_20210125_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectConsent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'single'), ('married', 'married'), ('divorced', 'divorced')], max_length=15, null=True, verbose_name='Are you single, married or divorced?')),
                ('stay_with', models.CharField(blank=True, choices=[('alone', 'alone'), ('partner', 'partner'), ('siblings', 'siblings'), ('other', 'other')], max_length=15, null=True, verbose_name='Who do you currently stay with?')),
            ],
        ),
    ]
