# Generated by Django 3.1.4 on 2021-01-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potlakosubject', '0004_subjectconsent'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectconsent',
            name='husbands',
            field=models.IntegerField(blank=True, choices=[('alone', 'alone'), ('partner', 'partner'), ('siblings', 'siblings'), ('other', 'other')], max_length=15, null=True, verbose_name='How many wives do you have, including traditional marriage?'),
        ),
        migrations.AddField(
            model_name='subjectconsent',
            name='wives',
            field=models.IntegerField(blank=True, choices=[('alone', 'alone'), ('partner', 'partner'), ('siblings', 'siblings'), ('other', 'other')], max_length=15, null=True, verbose_name='If wife, how many wives does your husband have (including traditional marriage), including yourself??'),
        ),
    ]
