# Generated by Django 3.1.4 on 2021-01-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potlakosubject', '0005_auto_20210125_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectconsent',
            name='husbands',
            field=models.IntegerField(blank=True, null=True, verbose_name='How many wives do you have, including traditional marriage?'),
        ),
        migrations.AlterField(
            model_name='subjectconsent',
            name='wives',
            field=models.IntegerField(blank=True, null=True, verbose_name='If wife, how many wives does your husband have (including traditional marriage), including yourself??'),
        ),
    ]
