# Generated by Django 3.1.4 on 2021-01-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potlakosubject', '0007_education'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name_plural': 'Education'},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name_plural': 'Enrollment'},
        ),
        migrations.AlterModelOptions(
            name='subjectconsent',
            options={'verbose_name_plural': 'Subject Consent'},
        ),
        migrations.AddField(
            model_name='education',
            name='recent_job',
            field=models.CharField(blank=True, choices=[('farmer', 'farmer(own land)'), ('farm_work_on_employers_land', 'farm work on employers land'), ('domestic_worker', 'domestic worker'), ('entertainment_venue', 'Work in bar/ hotel/ guest house/ entertainment venue'), ('fishing', 'fishing'), ('mining', 'mining'), ('tourism', 'tourism/game parks'), ('shop_small business', 'shop/small business'), ('informal_selling', 'informal_selling'), ('commercial_sex_work', 'commercial_sex_work'), ('transport', 'transport(trucker/ taxi driver'), ('factory_worker', 'factory_worker'), ('security_company', 'guard (security company)'), ('police_soldier', 'police/soldier'), ('clerical_office work', 'clerical /office work'), ('government_worker', 'government worker'), ('teacher', 'teacher'), ('health_care_worker', 'health_care_worker'), ('no_answer', 'dont want to answer'), ('other', 'other')], max_length=100, verbose_name='Describe the work that you do or did in your most recent job. If you have more than one profession, choose the one you spend the most time doing'),
        ),
        migrations.AddField(
            model_name='education',
            name='salary',
            field=models.CharField(blank=True, choices=[('none', 'none'), ('no_income', 'no income'), ('two_hundred', '1-199 pula'), ('five_hundred', '200-499 pula'), ('one_thousand', '500-999 pula'), ('five_thousand', '5000-10,000 pula'), ('above_ten_thousand', 'more than 10,000 pula'), ('no_answer', 'dont want to answer')], max_length=100, verbose_name='n the past month, how much money did you earn from work you did or received in payment?'),
        ),
    ]
