# Generated by Django 3.1.4 on 2021-01-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potlakosubject', '0008_auto_20210126_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityEngagementQuestionnare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activeness', models.CharField(blank=True, choices=[('very_active', 'very active'), ('somewhat_active', 'somewhat active'), ('not_active', 'not active at all'), ('no_answer', 'dont want to answer')], max_length=50, null=True, verbose_name='How active are you in community activities such as burial society, Motshelo, Syndicate, PTA, VDC(Village Development Committee), Mophato and development of the community that surrounds you?')),
                ('voting', models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no'), ('not_applicable', 'not applicable (no ,election , cant vote)'), ('no_answer', 'do not want to answer')], max_length=25, null=True, verbose_name='Did you vote in the last local government election?')),
                ('problems', models.CharField(blank=True, choices=[('hiv_aids', 'HIV/AIDS'), ('schools', 'schools'), ('sewer', 'sewer'), ('unemployment', 'unemployment'), ('roads', 'roads'), ('water', 'water'), ('house', 'house'), ('malaria', 'malaria')], max_length=25, null=True, verbose_name='What are the major problems in this neighborhood?')),
                ('neighborhood', models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no'), ('dont_know', 'do not know'), ('no_answer', 'do not want to answer')], max_length=25, null=True, verbose_name='If there is a problem in this neighborhood, do the adults work together in solving it?')),
            ],
        ),
    ]
