"""
Django settings for training project.

Generated by 'django-admin startproject' using Django 1.11.29.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
import sys
import configparser
from django.core.management.color import color_style

# from .logging import LOGGING
style = color_style()

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

APP_NAME = 'potlako_subject'

SITE_ID = 1

ETC_DIR = os.path.join(BASE_DIR, 'etc')

CONFIG_FILE = 'potlako.ini'

# CONFIG_PATH = os.path.join('/etc', 'potlako', CONFIG_FILE)
# sys.stdout.write(style.SUCCESS('f * Reading config from {CONFIG_FILE}\n'))
# config = configparser.ConfigParser()
# config.read(CONFIG_PATH)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'n8u8n#!uxnqj4_b(_6pd1z2_+q(vncx*laq-z_ox-*au&r3i@z'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    # 'django_crypto_fields.apps.AppConfig',
    'django_extensions',
    'rest_framework.authtoken',
    'potlakosubject',
    'crispy_forms',
    'edc_action_item.apps.AppConfig',
    # 'edc_sync.apps.AppConfig',
    # 'edc_sync_files.apps.AppConfig',
    # 'edc_base.apps.AppConfig',
    'edc_consent.apps.AppConfig',
    'edc_identifier.apps.AppConfig',
    'edc_locator.apps.AppConfig',
    'edc_reference.apps.AppConfig',
    'edc_metadata_rules.apps.AppConfig',
    'edc_registration.apps.AppConfig',
    'edc_timepoint.apps.AppConfig',
    # 'edc_visit_schedule.apps.AppConfig',
    'django_crypto_fields.apps.AppConfig',
    # 'potlako_metadata_rules.apps.AppConfig',
    # 'potlako_visit_schedule.apps.AppConfig',
    # 'potlako_reference.apps.AppConfig',
    # 'potlako_prn.apps.AppConfig',
    # 'potlako_subject.apps.EdcAppointmentAppConfig',
    # 'potlako_subject.apps.EdcFacilityAppConfig',
    # 'potlako_subject.apps.EdcMetadataAppConfig',
    # 'potlako_subject.apps.EdcProtocolAppConfig',
    # 'potlako_subject.apps.EdcDeviceAppConfig',
    # 'potlako_subject.apps.EdcVisitTrackingAppConfig',
    # 'potlako_subject.apps.AppConfig',
    # 'django_crypto_fields.apps.AppConfig',
    'edc_protocol',
]

# folder where the encryption keys are stored
# Do not set for tests
# KEY_PATH = '/etc/potlako/django_crypto_fields'

# optional filename prefix for encryption keys files:
# KEY_PREFIX = 'bhp066'

# AUTH_USER_MODEL = 'potlakosubject.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.sites.middleware.CurrentSiteMiddleware',
    'edc_dashboard.middleware.DashboardMiddleware',
    'edc_subject_dashboard.middleware.DashboardMiddleware',

]

ROOT_URLCONF = 'training.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        # 'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'training.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'sqlite3'),
    }
}

REST_FRAMEWORK = {
    'PAGE_SIZE': 1,
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
    ),
}

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
CRISPY_TEMPLATE_PACK = 'bootstrap4'

# Dashboards
DASHBOARD_URL_NAMES = {
    'subject_listboard_url': 'potlako_dashboard:subject_listboard_url',
    'screening_listboard_url': 'potlako_dashboard:screening_listboard_url',
    'subject_dashboard_url': 'potlako_dashboard:subject_dashboard_url',
}
# AUTO_CREATE_KEYS = True
